### ISSUE TITLE
PC端打开页面时，无法滑动日期控件

### ISSUE THREAD

**Issue by morongs** [youzan/vant#1145]
想问一下，我看官网的这个案例：
https://www.youzanyun.com/zanui/vant/examples#/zh-CN/datetime-picker?rand=1527046061623 
用PC浏览器打开的，可以使用鼠标滑动，但是做到我们的项目中，却滑动不了只能点击。
![image](https://user-images.githubusercontent.com/8064956/40414036-dc482c62-5ea9-11e8-996b-872b20033639.png)
 
想问下是版本问题吗？

**Comment by Kimstroy** [comment]
貌似PC端没有touchmove事件发自我的iPhone------------------ 原始邮件 ------------------发件人: 默容  <notifications@github.com>发送时间: 2018年5月23日 16:54收件人: youzan/vant <vant@noreply.github.com>抄送: Subscribed <subscribed@noreply.github.com>主题: 回复：[youzan/vant] PC端打开页面时，无法滑动日期控件 (#1145)想问一下，我看官网的这个案例：
https://www.youzanyun.com/zanui/vant/examples#/zh-CN/datetime-picker?rand=1527046061623
用PC浏览器打开的，可以使用鼠标滑动，但是做到我们的项目中，却滑动不了只能点击。

想问下是版本问题吗？

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/youzan/vant/issues/1145","url":"https://github.com/youzan/vant/issues/1145","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/youzan/vant","title":"youzan/vant","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/youzan/vant"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"PC端打开页面时，无法滑动日期控件 (#1145)"}],"action":{"name":"View Issue","url":"https://github.com/youzan/vant/issues/1145"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "37567f93-e2a7-4e2a-ad37-a9160fc62647",
"title": "PC端打开页面时，无法滑动日期控件 (#1145)",
"sections": [
{
"text": "",
"activityTitle": "**默容**",
"activityImage": "https://avatars3.githubusercontent.com/u/8064956?s=160\u0026v=4",
"activitySubtitle": "@morongs",
"facts": [
{
"name": "Repository: ",
"value": "youzan/vant"
},
{
"name": "Issue #: ",
"value": 1145
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"youzan/vant\",\n\"issueId\": 1145,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"youzan/vant\",\n\"issueId\": 1145\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/youzan/vant/issues/1145"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 338174694\n}"
}
],
"themeColor": "26292E"
}

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/637
