### ISSUE TITLE
[Bug Report] van-popup报错Cannot set property 'zIndex' of undefined

### ISSUE THREAD

**Issue by nicksun011** [youzan/vant#3753]
### 设备 / 浏览器
Chrome

### Vant 版本
2.0.5

### Vue版本
2.5.2

### 重现链接
<a href="https://xxxx.com" target="_blank">https://xxxx.com</a>

### 描述问题
程序打包后调用van-popup，直接报错Cannot set property 'zIndex' of undefined，里面只是写了一个div。
本机调试时正常，但是打包后就会出现这个问题。

**Comment by chenjiahan** [comment]
复现链接无法打开，麻烦提供正确的复现链接

**Comment by nicksun011** [comment]
因为我工程层级比较深，http://test-app01.yugusoft.com/ftask/mobile/index.html#/login，102136/123456，账户密码，然后登入。复现路径：首页工作台-》财务审批-》右下角新建差旅报销，选择开始时间或结束

**Comment by nicksun011** [comment]
这个比较特殊的地方就是，新建差旅报销界面本身position是fixed的

**Comment by nicksun011** [comment]
试了试简单界面使用popup，也是这个问题

**Comment by chenjiahan** [comment]
没复现问题，最好提供个 codesandbox 链接

**Comment by nicksun011** [comment]
codesandbox应该不会出现这个问题，不知道和我打包的环境有没有关系

**Comment by chenjiahan** [comment]
嗯，建议先检查下打包的配置，自行调试下

**Comment by JacobMa1996** [comment]
> 嗯，建议先检查下打包的配置，自行调试下

请问下这个问题有结论吗？我也遇到了

**Comment by bubbletxw** [comment]
我也遇到了  把node_modules删了重新install一下就好了

**Comment by xiaosatufu** [comment]
删除node_modlues并不能解决问题，从2.0.5到2.1.1 popup插件好像都会存在这个问题。不知道怎么解决，官方也没有给解决方案。

**Comment by xiaosatufu** [comment]
[Vue warn]: Error in nextTick: "TypeError: Cannot set property 'zIndex' of undefined"
TypeError: Cannot set property 'zIndex' of undefined

**Comment by topul** [comment]
开了vue-devtools就有很大概率会出现这个问题，关了就不会，不知道是不是有冲突，还经常会报死循环
![image](https://user-images.githubusercontent.com/8213229/66044668-ad5bd100-e554-11e9-861a-b2c12ea4772b.png)

**Comment by fanfanjiang** [comment]
我也遇到了，头疼

**Comment by edgexie** [comment]
我也遇到了

**Comment by aloneWang** [comment]
我也遇到了，不过我这错误环境是：单页面是通过iframe插进去的， debug时，this.$el指向的是注释，当前组件并未挂载到dom上。我目前就就给外层div加了v-show 预渲染下解决了，不知道和你们报错的问题原因是否一样。

**Comment by lifuyao** [comment]
这个问题有没有解决啊，我也遇到了这个问题
![image](https://user-images.githubusercontent.com/21291355/80297514-299a5800-87b6-11ea-8b18-cb8c651e6c39.png)

**Comment by lifuyao** [comment]
搞定了，
new Vue({
  el: '#app',
  router,
  store,
  render: h => h(App)
}).$mount("#app")

把vue升级成2.6.10，就不出现这个问题了

**Comment by zhang156** [comment]
Vue@2.6.10;Vant@2.8.1
我这边也是出现了同样的问题，看别的issue说是vue多次引入，删了node_modules后重新下载后解决。

**Comment by haringsrob** [comment]
I managed to solve this on my end after quite a lot of debugging.

It was even stranger because I could not reproduce this on my local development environment.

What in the end did the trick was to configure in my `vue.config.js` the following highlighted line:

<img width="733" alt="Screenshot 2020-05-19 at 14 16 42" src="https://user-images.githubusercontent.com/866743/82325632-d47beb80-99db-11ea-8945-8a257befe7db.png">

```vue$: path.resolve(__dirname, 'node_modules/vue/dist/vue.runtime.esm.js'),``` is what did the tricker. 

I also tried with how it is described here: https://vuejs.org/v2/guide/installation.html#Runtime-Compiler-vs-Runtime-only (`'vue$': 'vue/dist/vue.esm.js'`) but that did not work.

Vant is the only package I have this issue with. It might be slightly connected but I am not sure.

I hope the above will help others to resolve this issue.

**Comment by lanbin1017** [comment]
vconsole.min.js:10 [Vue warn]: Error in nextTick: "TypeError: Cannot set property 'zIndex' of undefined"
同样遇到了，我试下重装包吧

**Comment by JGX19** [comment]
我这边遇到这种情况的问题是因为在popup里用了picker，但是我的picker在某些初始情况下columns赋了null，导致报错，改一下columns的默认赋值就好了。
