### ISSUE TITLE
请问van-tree-select 左侧的van-sidebar无法渲染出来是什么问题？

### ISSUE THREAD

**Issue by Neokekeke** [youzan/vant#6119]
**代码**
```
        <van-tree-select
            height="55vw"
            :items="items"
            :main-active-index="active"
        >
            <template slot="content">
                <van-image
                    v-if="active == 0"
                    src="https://img.yzcdn.cn/vant/apple-1.jpg"
                />
                <van-image
                    v-if="active == 1"
                    src="https://img.yzcdn.cn/vant/apple-2.jpg"
                />
            </template>
        </van-tree-select>
```

**错误**
Error in render function: "TypeError: Cannot read property 'children' of undefined"
found in
---> <VanSidebarItem>
       <VanSidebar>

Cannot read property 'children' of undefined at VueComponent.ChildrenMixin.__WEBPACK_IMPORTED_MODULE_0_vue__.default.extend.computed._computed.

**Comment by Neokekeke** [comment]
问题原因是vue版本过低导致

**Comment by gcindy** [comment]
我微信小程序可以 app运行报错:
20:57:31.915 [ERROR] : cid unmatched [object Object]
20:57:31.949 [ERROR] : TypeError: Invalid attempt to destructure non-iterable instance.
20:57:31.949 In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
20:57:32.000 [ERROR] : Not found -1,2;-1,2,3,4-0;undefined

请问怎么解决
