### ISSUE TITLE
[Bug Report] tab   list 子tab 中的list触发onload事件，其它子Tab也会触发执行onload事件。

### ISSUE THREAD

**Issue by AmKang** [youzan/vant#8729]
### 设备 / 浏览器
chrome

### Vant 版本
3.0.0

### Vue 版本
3.0.0

### 重现链接
<a href="http://localhost:8080/#/index2" target="_blank">http://localhost:8080/#/index2</a>

### 描述问题
作者您好，现有应用场景如下：页面有2个tab，每个tab下都有自己的list。当只浏览某项tab数据时，触发当前list的onload事件，但另一个tab中的list也会触发执行onload事件。
部分代码如下：
主页面（包含子页面1和子页面2）
![QQ截图20210520171901](https://user-images.githubusercontent.com/43641341/118953654-9bc87680-b98f-11eb-9b15-20eec0f18df7.png)
子页面1
![QQ截图20210520171919](https://user-images.githubusercontent.com/43641341/118953738-ac78ec80-b98f-11eb-921e-66faf51db902.png)

子页面2
![QQ截图20210520171830](https://user-images.githubusercontent.com/43641341/118953752-b00c7380-b98f-11eb-9b5e-664e46d41ef3.png)

[在之前issue中](https://github.com/youzan/vant/issues/2387) 看到有类似问题，请问3.0版本也是解决了吗？感谢拨冗解答。

**Comment by chenjiahan** [comment]
问题的原因参见：https://github.com/youzan/vant/issues/3430

目前 3.0 中未处理这种场景，后续会添加一下兼容逻辑

**Comment by chenjiahan** [comment]
已在 3.0.17 版本修复

**Comment by Linhongbin-1111** [comment]
> 已在 3.0.17 版本修复

请问 vant2 会进行修复吗

**Comment by chenjiahan** [comment]
木有计划喔

**Comment by Linhongbin-1111** [comment]
好的谢谢，早点休息哦！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月12日(周四) 晚上11:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [youzan/vant] [Bug Report] tab   list 子tab 中的list触发onload事件，其它子Tab也会触发执行onload事件。 (#8729)




 
木有计划喔
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chenjiahan** [comment]
^_^
